services:
  agenda_psql:
    container_name: agenda_psql
    restart: unless-stopped
    build:
      context: .
    networks:
      - proxy
      - default
    volumes:
      - ./static:/data/web/static
      - ./media:/data/web/media
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"                                                 
      - "traefik.http.routers.agenda.rule=Host(`agenda.docker.localhost`)"             
      - "traefik.http.routers.agenda.entrypoints=websecure"                    
      - "traefik.http.routers.agenda.tls=true"   
      - "traefik.http.services.agenda.loadbalancer.server.port=8000"
  
  nginx-static-agenda:
    container_name: nginx-static-agenda
    restart: unless-stopped
    image: nginx:alpine
    networks:
      - proxy
    volumes:
      - ./static:/data/web/static:ro
      - ./media:/data/web/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-agenda.rule=Host(`agenda.docker.localhost`) && (PathPrefix(`/static/`) || PathPrefix(`/media/`))"
      - "traefik.http.routers.static-agenda.entrypoints=websecure"
      - "traefik.http.routers.static-agenda.tls=true"   
      - "traefik.http.services.static-agenda.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: blog_default
  proxy:
    external: true                      
